### ISSUE TITLE
Can not turn with mouse in Minecraft

### ISSUE THREAD

**Issue by solt6626** [berlius/DeepLearningDockerfile#4]
I managed to start the Minecraft from lxterminal. Thank you for all your help. One last problem is that I can not use the mouse. My agent does not turn when I move the mouse. Instead I see the mouse pointer. Any advise? Thanks!

**Comment by berlius** [comment]
congratulations !  here is a first step completed

**"One last problem is that I can not use the mouse"**

Yes it's normal. This was foreseen by the program designers. Here is an excerpt of the manual (page 5)

The platform disables mouse control of Minecraft by default, in order to
prevent accidental mouse movements from affecting experiments. To explore
the Minecraft world you have decorated, you can toggle between human and
platform mouse control – click on the Minecraft window and press Enter to
switch. Once you have control, explore the world using the mouse, and the W,
S, A and D keys (assuming you have the default Minecraft setup.) The
platform will automatically re-take control at the start of each mission.

from : [Manual Tutorial (page 5)](http://microsoft.github.io/malmo/0.17.0/Python_Examples/Tutorial.pdf)
